Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 5, in <module>
    matplotlib.pyplot
NameError: name 'matplotlib' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 5, in <module>
    matplotlib.pyplot
NameError: name 'matplotlib' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Warning (from warnings module):
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 273
    warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.

===================== RESTART: /home/user/RTR105/1B1.py =====================

Warning (from warnings module):
  File "/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py", line 273
    warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 6, in <module>
    matplotlib.pyplot
NameError: name 'matplotlib' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 6, in <module>
    matplotlib.pyplot
NameError: name 'matplotlib' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 6, in <module>
    matplotlib.pyplot
NameError: name 'matplotlib' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
